services:
  - type: web
    name: deriv-trading-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python your_script_name.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: seu_token_aqui
      - key: TELEGRAM_CHAT_ID  
        value: seu_chat_id